-- unlimitail_fr__validation.cv_r_product_attribute_relation definition

CREATE REFERENCE TABLE `cv_r_product_attribute_relation` (
  `retailer_id` smallint(6) DEFAULT NULL,
  `internal_id` int(11) NOT NULL,
  `attribute_id` int(11) NOT NULL,
  `attribute_value_id` int(11) NOT NULL,
  SORT KEY `internal_id` (`internal_id`,`attribute_id`,`attribute_value_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_product_parents_flat definition

CREATE REFERENCE TABLE `cv_r_product_parents_flat` (
  `retailer_id` smallint(6) DEFAULT NULL,
  `catalog_internal_id` int(11) NOT NULL,
  `cv_hier_1_level_1` int(11) NOT NULL,
  `cv_hier_1_level_2` int(11) NOT NULL,
  `cv_hier_1_level_3` int(11) NOT NULL,
  `cv_hier_1_level_4` int(11) NOT NULL,
  `cv_hier_1_level_5` int(11) NOT NULL,
  `cv_hier_2_level_0` int(11) NOT NULL,
  `cv_hier_2_level_1` int(11) NOT NULL,
  `cv_hier_2_level_2` int(11) NOT NULL,
  `cv_hier_2_level_3` int(11) NOT NULL,
  `cv_hier_4_level_0` int(11) NOT NULL,
  `cv_hier_4_level_1` int(11) NOT NULL,
  `cv_hier_4_level_2` int(11) NOT NULL,
  `cv_hier_4_level_3` int(11) NOT NULL,
  `cv_hier_12_level_0` int(11) DEFAULT NULL,
  `cv_hier_12_level_1` int(11) DEFAULT NULL,
  `cv_hier_13_level_0` int(11) DEFAULT NULL,
  `cv_hier_13_level_1` int(11) DEFAULT NULL,
  `cv_hier_14_level_0` int(11) DEFAULT NULL,
  `cv_hier_14_level_1` int(11) DEFAULT NULL,
  `cv_hier_15_level_0` int(11) DEFAULT NULL,
  `cv_hier_15_level_1` int(11) DEFAULT NULL,
  `cv_hier_15_level_2` int(11) DEFAULT NULL,
  `cv_hier_15_level_3` int(11) DEFAULT NULL,
  `access_roles_1` varbinary(2000) DEFAULT ',',
  `access_roles_2` varbinary(2000) DEFAULT ',',
  `access_roles_4` varbinary(2000) DEFAULT ',',
  `access_roles_12` varbinary(2000) DEFAULT ',',
  `access_roles_13` varbinary(2000) DEFAULT ',',
  `access_roles_14` varbinary(2000) DEFAULT ',',
  `access_roles_15` varbinary(2000) DEFAULT ',',
  `product_attr_access_roles` varbinary(2000) DEFAULT ',',
  `product_barcode` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  SORT KEY `catalog_internal_id_const` (`catalog_internal_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_purchase_history_all definition

CREATE TABLE `cv_r_purchase_history_all` (
  `retailer_id` smallint(6) DEFAULT NULL,
  `cv_shopper_id` int(11) NOT NULL,
  `cv_membership_id` int(11) DEFAULT NULL,
  `invoice_id` varchar(120) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `cv_invoice_id` bigint(20) NOT NULL,
  `catalog_internal_id` int(11) NOT NULL,
  `cv_pos_id` smallint(6) NOT NULL,
  `shopping_date` timestamp NULL DEFAULT NULL,
  `purchase_date` date NOT NULL,
  `purchase_units` double NOT NULL,
  `purchase_uom_qty` double DEFAULT NULL,
  `purchase_discount` double NOT NULL,
  `purchase_discount_local` double DEFAULT NULL COMMENT 'purchase_discount local currency value' ,
  `local_currency_code` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'the local iso currency code' ,
  `positive_purchase_spent` tinyint(4) NOT NULL,
  `purchase_spent` double NOT NULL,
  `gross_margin` double DEFAULT NULL,
  `net_margin` double DEFAULT NULL,
  `cost_price` double DEFAULT NULL,
  `purchase_spent_no_tax` double NOT NULL,
  `purchase_discount_no_tax` double NOT NULL,
  `purchase_spent_local` double NOT NULL,
  `gross_margin_local` double DEFAULT NULL,
  `net_margin_local` double DEFAULT NULL,
  `cost_price_local` double DEFAULT NULL,
  `purchase_spent_no_tax_local` double NOT NULL,
  `purchase_discount_no_tax_local` double NOT NULL,
  `attribute_s_1` int(11) DEFAULT NULL,
  `attribute_s_2` int(11) DEFAULT NULL,
  `attribute_s_3` int(11) DEFAULT NULL,
  `attribute_s_4` int(11) DEFAULT NULL,
  `attribute_s_5` int(11) DEFAULT NULL,
  `attribute_s_6` int(11) DEFAULT NULL,
  `attribute_s_7` int(11) DEFAULT NULL,
  `attribute_s_8` int(11) DEFAULT NULL,
  `attribute_s_9` int(11) DEFAULT NULL,
  `attribute_s_10` int(11) DEFAULT NULL,
  `attribute_c_1` int(11) DEFAULT NULL,
  `attribute_c_2` int(11) DEFAULT NULL,
  `attribute_c_3` int(11) DEFAULT NULL,
  `attribute_c_4` int(11) DEFAULT NULL,
  `attribute_c_5` int(11) DEFAULT NULL,
  `attribute_c_6` int(11) DEFAULT NULL,
  `attribute_c_7` int(11) DEFAULT NULL,
  `attribute_c_8` int(11) DEFAULT NULL,
  `attribute_c_9` int(11) DEFAULT NULL,
  `attribute_c_10` int(11) DEFAULT NULL,
  `attribute_c_11` int(11) DEFAULT NULL,
  `attribute_c_12` int(11) DEFAULT NULL,
  `attribute_c_13` int(11) DEFAULT NULL,
  `attribute_c_14` int(11) DEFAULT NULL,
  `attribute_c_15` int(11) DEFAULT NULL,
  `attribute_c_16` int(11) DEFAULT NULL,
  `attribute_c_17` int(11) DEFAULT NULL,
  `attribute_c_18` int(11) DEFAULT NULL,
  `attribute_c_19` int(11) DEFAULT NULL,
  `attribute_c_20` int(11) DEFAULT NULL,
  `attribute_c_21` int(11) DEFAULT NULL,
  `attribute_c_22` int(11) DEFAULT NULL,
  `attribute_c_23` int(11) DEFAULT NULL,
  `attribute_c_24` int(11) DEFAULT NULL,
  `attribute_c_25` int(11) DEFAULT NULL,
  `attribute_c_26` int(11) DEFAULT NULL,
  `attribute_c_27` int(11) DEFAULT NULL,
  `attribute_c_28` int(11) DEFAULT NULL,
  `attribute_c_29` int(11) DEFAULT NULL,
  `attribute_c_30` int(11) DEFAULT NULL,
  SORT KEY `purchase_date` (`purchase_date`,`cv_shopper_id`,`catalog_internal_id`,`cv_pos_id`,`cv_invoice_id`),
  SHARD KEY `cv_shopper_id` (`cv_shopper_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_shopping_attributes_all definition

CREATE TABLE `cv_r_shopping_attributes_all` (
  `retailer_id` smallint(6) DEFAULT NULL,
  `cv_shopper_id` int(11) NOT NULL,
  `cv_product_item_id` bigint(20) NOT NULL,
  `rfv_tier_id` smallint(6) DEFAULT NULL,
  `rfv_tier` smallint(6) NOT NULL,
  `tier_trend_id` smallint(6) DEFAULT NULL,
  `tier_trend` smallint(6) DEFAULT NULL,
  `basket_value_id` bigint(20) DEFAULT NULL,
  `basket_value` decimal(12,2) DEFAULT NULL,
  `basket_units_id` bigint(20) DEFAULT NULL,
  `basket_units` decimal(12,2) DEFAULT NULL,
  `frequency_id` smallint(6) DEFAULT NULL,
  `frequency` smallint(6) DEFAULT NULL,
  `recency_id` smallint(6) DEFAULT NULL,
  `recency` smallint(6) NOT NULL,
  `first_id` smallint(6) DEFAULT NULL,
  `first` smallint(6) DEFAULT NULL,
  `churn_id` smallint(6) DEFAULT NULL,
  `churn` smallint(6) DEFAULT NULL,
  `long_period_value_id` bigint(20) DEFAULT NULL,
  `long_period_value` decimal(12,2) DEFAULT NULL,
  `long_period_value_discount_percentage_id` bigint(20) DEFAULT NULL,
  `short_period_value` decimal(12,2) DEFAULT NULL,
  `long_period_visits_number` int(11) DEFAULT NULL,
  `short_period_visits_number` int(11) DEFAULT NULL,
  `short_period_value_discount_percentage` decimal(5,2) DEFAULT NULL,
  `long_period_value_discount_percentage` decimal(5,2) DEFAULT NULL,
  `visited_weeks` int(11) DEFAULT NULL,
  `wallet_share_id` smallint(6) DEFAULT NULL,
  `wallet_share` decimal(12,2) DEFAULT NULL,
  `relevancy_score` decimal(6,6) DEFAULT NULL,
  `nbo_id` smallint(6) DEFAULT NULL,
  `digital_wallet_share_id` smallint(6) DEFAULT NULL,
  `digital_wallet_share` decimal(12,2) DEFAULT NULL,
  SORT KEY `cv_product_item_id` (`cv_product_item_id`,`cv_shopper_id`),
  SHARD KEY `__SHARDKEY` (`cv_shopper_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_shopping_brand_attributes definition

CREATE TABLE `cv_r_shopping_brand_attributes` (
  `retailer_id` smallint(6) DEFAULT NULL,
  `cv_shopper_id` int(11) NOT NULL,
  `catalog_internal_id` bigint(20) NOT NULL,
  `recency` smallint(6) NOT NULL,
  `first` smallint(6) NOT NULL,
  `period_value` decimal(12,2) DEFAULT NULL,
  `life_value` decimal(12,2) DEFAULT NULL,
  `life_units` decimal(12,2) DEFAULT NULL,
  `long_period_value` decimal(12,2) DEFAULT NULL,
  `long_period_line_discount_percentage` decimal(5,2) DEFAULT NULL,
  `brand_loyalty_index` smallint(6) DEFAULT NULL,
  `short_period_value` decimal(12,2) DEFAULT NULL,
  `short_period_value_discount_percentage` decimal(5,2) DEFAULT NULL,
  `long_period_value_discount_percentage` decimal(5,2) DEFAULT NULL,
  `short_period_line_discount_percentage` decimal(5,2) DEFAULT NULL,
  `visited_weeks` bigint(20) DEFAULT NULL,
  `yearly_spent_value` decimal(12,2) DEFAULT NULL,
  `relevancy_score` decimal(6,6) DEFAULT NULL,
  `nbo_id` smallint(6) DEFAULT NULL,
  SORT KEY `cv_shopper_id` (`cv_shopper_id`,`catalog_internal_id`),
  SHARD KEY `__SHARDKEY` (`cv_shopper_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_shopping_brand_attributes_history_dim_all definition

CREATE TABLE `cv_r_shopping_brand_attributes_history_dim_all` (
  `cv_shopper_id` int(11) NOT NULL,
  `catalog_internal_id` int(11) NOT NULL,
  `cv_brand_id` int(11) NOT NULL,
  `attribute_id` smallint(6) NOT NULL,
  `attribute_value_id` smallint(6) NOT NULL,
  `from_date` date NOT NULL,
  `to_date` date DEFAULT NULL,
  SORT KEY `from_date` (`from_date`,`to_date`,`attribute_id`,`attribute_value_id`,`cv_brand_id`,`catalog_internal_id`,`cv_shopper_id`),
  SHARD KEY `__SHARDKEY` (`cv_shopper_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_shpr_active_period_dim definition

CREATE TABLE `cv_r_shpr_active_period_dim` (
  `cv_shopper_id` int(11) NOT NULL,
  `from_date` date NOT NULL,
  `to_date` date DEFAULT NULL,
  SORT KEY `from_date` (`from_date`,`cv_shopper_id`),
  SHARD KEY `__SHARDKEY` (`cv_shopper_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_shpr_attributes_dim_all definition

CREATE TABLE `cv_r_shpr_attributes_dim_all` (
  `retailer_id` smallint(6) DEFAULT NULL,
  `cv_shopper_id` int(11) NOT NULL,
  `shopper_rtlr_loyalty_id` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `preferred_pos_id` smallint(6) DEFAULT NULL,
  `eligibility_channels` int(11) DEFAULT NULL,
  `security_hierarchy_id` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `age` smallint(6) DEFAULT NULL,
  `attribute_0` int(11) DEFAULT NULL,
  `attribute_0_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_100` int(11) DEFAULT NULL,
  `attribute_100_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_1` int(11) DEFAULT NULL,
  `attribute_1_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_2` int(11) DEFAULT NULL,
  `attribute_2_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_3` int(11) DEFAULT NULL,
  `attribute_3_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_4` int(11) DEFAULT NULL,
  `attribute_4_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_5` int(11) DEFAULT NULL,
  `attribute_5_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_6` int(11) DEFAULT NULL,
  `attribute_6_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_7` int(11) DEFAULT NULL,
  `attribute_7_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_8` int(11) DEFAULT NULL,
  `attribute_8_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_9` int(11) DEFAULT NULL,
  `attribute_9_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_10` int(11) DEFAULT NULL,
  `attribute_10_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_11` int(11) DEFAULT NULL,
  `attribute_11_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_12` int(11) DEFAULT NULL,
  `attribute_12_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_13` int(11) DEFAULT NULL,
  `attribute_13_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_14` int(11) DEFAULT NULL,
  `attribute_14_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_15` int(11) DEFAULT NULL,
  `attribute_15_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_16` int(11) DEFAULT NULL,
  `attribute_16_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_17` int(11) DEFAULT NULL,
  `attribute_17_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_18` int(11) DEFAULT NULL,
  `attribute_18_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_19` int(11) DEFAULT NULL,
  `attribute_19_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_20` int(11) DEFAULT NULL,
  `attribute_20_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_21` int(11) DEFAULT NULL,
  `attribute_21_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_22` int(11) DEFAULT NULL,
  `attribute_22_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_23` int(11) DEFAULT NULL,
  `attribute_23_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_24` int(11) DEFAULT NULL,
  `attribute_24_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_25` int(11) DEFAULT NULL,
  `attribute_25_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_26` int(11) DEFAULT NULL,
  `attribute_26_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_27` int(11) DEFAULT NULL,
  `attribute_27_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_28` int(11) DEFAULT NULL,
  `attribute_28_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_29` int(11) DEFAULT NULL,
  `attribute_29_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_30` int(11) DEFAULT NULL,
  `attribute_30_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_31` int(11) DEFAULT NULL,
  `attribute_31_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_32` int(11) DEFAULT NULL,
  `attribute_32_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_33` int(11) DEFAULT NULL,
  `attribute_33_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_34` int(11) DEFAULT NULL,
  `attribute_34_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_35` int(11) DEFAULT NULL,
  `attribute_35_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_36` int(11) DEFAULT NULL,
  `attribute_36_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_37` int(11) DEFAULT NULL,
  `attribute_37_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_38` int(11) DEFAULT NULL,
  `attribute_38_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_39` int(11) DEFAULT NULL,
  `attribute_39_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_40` int(11) DEFAULT NULL,
  `attribute_40_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_41` int(11) DEFAULT NULL,
  `attribute_41_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_42` int(11) DEFAULT NULL,
  `attribute_42_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_43` int(11) DEFAULT NULL,
  `attribute_43_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_44` int(11) DEFAULT NULL,
  `attribute_44_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_45` int(11) DEFAULT NULL,
  `attribute_45_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_46` int(11) DEFAULT NULL,
  `attribute_46_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_101` int(11) DEFAULT NULL,
  `attribute_101_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_102` int(11) DEFAULT NULL,
  `attribute_102_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_103` int(11) DEFAULT NULL,
  `attribute_103_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_104` int(11) DEFAULT NULL,
  `attribute_104_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_105` int(11) DEFAULT NULL,
  `attribute_105_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_106` int(11) DEFAULT NULL,
  `attribute_106_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_107` int(11) DEFAULT NULL,
  `attribute_107_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_108` int(11) DEFAULT NULL,
  `attribute_108_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_109` int(11) DEFAULT NULL,
  `attribute_109_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_110` int(11) DEFAULT NULL,
  `attribute_110_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_111` int(11) DEFAULT NULL,
  `attribute_111_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_112` int(11) DEFAULT NULL,
  `attribute_112_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_113` int(11) DEFAULT NULL,
  `attribute_113_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_114` int(11) DEFAULT NULL,
  `attribute_114_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_115` int(11) DEFAULT NULL,
  `attribute_115_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_116` int(11) DEFAULT NULL,
  `attribute_116_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_117` int(11) DEFAULT NULL,
  `attribute_117_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_118` int(11) DEFAULT NULL,
  `attribute_118_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_119` int(11) DEFAULT NULL,
  `attribute_119_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_120` int(11) DEFAULT NULL,
  `attribute_120_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_121` int(11) DEFAULT NULL,
  `attribute_121_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_122` int(11) DEFAULT NULL,
  `attribute_122_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_123` int(11) DEFAULT NULL,
  `attribute_123_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_124` int(11) DEFAULT NULL,
  `attribute_124_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_125` int(11) DEFAULT NULL,
  `attribute_125_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_126` int(11) DEFAULT NULL,
  `attribute_126_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_127` int(11) DEFAULT NULL,
  `attribute_127_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_128` int(11) DEFAULT NULL,
  `attribute_128_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_129` int(11) DEFAULT NULL,
  `attribute_129_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_130` int(11) DEFAULT NULL,
  `attribute_130_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_131` int(11) DEFAULT NULL,
  `attribute_131_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_132` int(11) DEFAULT NULL,
  `attribute_132_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_133` int(11) DEFAULT NULL,
  `attribute_133_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_134` int(11) DEFAULT NULL,
  `attribute_134_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_135` int(11) DEFAULT NULL,
  `attribute_135_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_136` int(11) DEFAULT NULL,
  `attribute_136_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_137` int(11) DEFAULT NULL,
  `attribute_137_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_138` int(11) DEFAULT NULL,
  `attribute_138_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_139` int(11) DEFAULT NULL,
  `attribute_139_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_140` int(11) DEFAULT NULL,
  `attribute_140_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_141` int(11) DEFAULT NULL,
  `attribute_141_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_142` int(11) DEFAULT NULL,
  `attribute_142_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_143` int(11) DEFAULT NULL,
  `attribute_143_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_144` int(11) DEFAULT NULL,
  `attribute_144_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_145` int(11) DEFAULT NULL,
  `attribute_145_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_146` int(11) DEFAULT NULL,
  `attribute_146_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_147` int(11) DEFAULT NULL,
  `attribute_147_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_148` int(11) DEFAULT NULL,
  `attribute_148_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_149` int(11) DEFAULT NULL,
  `attribute_149_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `attribute_150` int(11) DEFAULT NULL,
  `attribute_150_value` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  SORT KEY `cv_shopper_id` (`cv_shopper_id`),
  SHARD KEY `__SHARDKEY` (`cv_shopper_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_shpr_attributes_history_dim definition

CREATE TABLE `cv_r_shpr_attributes_history_dim` (
  `retailer_id` smallint(6) DEFAULT NULL,
  `cv_shopper_id` int(11) NOT NULL,
  `attribute_id` smallint(6) NOT NULL,
  `attribute_value_id` smallint(6) NOT NULL,
  `from_date` date NOT NULL,
  `to_date` date DEFAULT NULL,
  SORT KEY `attribute_id` (`attribute_id`,`from_date`,`to_date`,`cv_shopper_id`),
  SHARD KEY `__SHARDKEY` (`cv_shopper_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_shpr_removal_history definition

CREATE TABLE `cv_r_shpr_removal_history` (
  `cv_shopper_id` int(11) NOT NULL,
  `loyalty_id` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `deletion_policy` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `timestamp_created` timestamp NULL DEFAULT NULL,
  SORT KEY `cv_shopper_id` (`cv_shopper_id`),
  SHARD KEY `__SHARDKEY` (`cv_shopper_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';


-- unlimitail_fr__validation.cv_r_store_parents_flat definition

CREATE REFERENCE TABLE `cv_r_store_parents_flat` (
  `retailer_id` smallint(6) DEFAULT NULL,
  `cv_pos_id` int(11) NOT NULL,
  `cv_hier_3_level_1` int(11) NOT NULL,
  `cv_hier_3_level_2` int(11) NOT NULL,
  `cv_hier_3_level_3` int(11) NOT NULL,
  `cv_hier_3_level_4` int(11) NOT NULL,
  `cv_hier_3_level_5` int(11) NOT NULL,
  `cv_hier_5_level_1` int(11) NOT NULL,
  `cv_hier_5_level_2` int(11) NOT NULL,
  `cv_hier_5_level_3` int(11) NOT NULL,
  `cv_hier_5_level_4` int(11) NOT NULL,
  `cv_hier_5_level_5` int(11) NOT NULL,
  `cv_hier_9_level_1` int(11) NOT NULL,
  `cv_hier_9_level_2` int(11) NOT NULL,
  `cv_hier_9_level_3` int(11) NOT NULL,
  `cv_hier_9_level_4` int(11) NOT NULL,
  `cv_hier_9_level_5` int(11) NOT NULL,
  `cv_hier_11_level_1` int(11) NOT NULL,
  `cv_hier_11_level_2` int(11) NOT NULL,
  `cv_hier_11_level_3` int(11) NOT NULL,
  `cv_hier_11_level_4` int(11) NOT NULL,
  `cv_hier_11_level_5` int(11) NOT NULL,
  `cv_hier_17_level_1` int(11) NOT NULL,
  `cv_hier_17_level_2` int(11) NOT NULL,
  `cv_hier_17_level_3` int(11) NOT NULL,
  `cv_hier_17_level_4` int(11) NOT NULL,
  `cv_hier_17_level_5` int(11) NOT NULL,
  `access_roles_3` varbinary(2000) DEFAULT ',',
  `access_roles_5` varbinary(2000) DEFAULT ',',
  `access_roles_9` varbinary(2000) DEFAULT ',',
  `access_roles_11` varbinary(2000) DEFAULT ',',
  `access_roles_17` varbinary(2000) DEFAULT ',',
  `store_attr_access_roles` varbinary(2000) DEFAULT ',',
  `same_pos` smallint(6) DEFAULT NULL,
  SORT KEY `cv_pos_id_const` (`cv_pos_id`)
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES';